<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>IFASBrowser</AssemblyName>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
</Project>
